#!/bin/sh -e

# serial tests, but still compile against MPI libraries
DEFAULT_MPI=$( grep ARCH_DEFAULT_MPI_IMPL /usr/share/mpi-default-dev/debian_defaults | sed "s/ARCH_DEFAULT_MPI_IMPL=//" )

# full 64-bit all integers. We're not ready for this.
#OPTC_64BIT=-DINTSIZE64 -DPORD_INTSIZE64
#OPTF_64BIT=-fdefault-integer-8

# 64 bit in MUMPS ordering (PORD) only
OPTC_64BIT=-DPORD_INTSIZE64
OPTF_64BIT=

BUILD_FLAGS_64BIT=OPTC_64BIT="${OPTC_64BIT}" OPTF_64BIT="${OPTF_64BIT}"

cd examples

cp ../debian/tests/Makefile.inc ..
make clean
make MUMPS_MPI=${DEFAULT_MPI} ${BUILD_FLAGS_64BIT} PLAT="_64pord" all

echo "\n=== running 64-bit c_example (serial) ==="
./c_example
./c_example_save_restore

echo "\n\n=== running 64-bit simple test: real, single precision, serial ==="
./ssimpletest < input_simpletest_real
./ssimpletest_save_restore < input_simpletest_real

echo "\n\n=== running 64-bit simple test: real, double precision, serial ==="
./dsimpletest < input_simpletest_real
./dsimpletest_save_restore < input_simpletest_real

echo "\n\n=== running 64-bit simple test: complex, single precision, serial ==="
./csimpletest < input_simpletest_cmplx
./csimpletest_save_restore < input_simpletest_cmplx

echo "\n\n=== running 64-bit simple test: complex, double precision, serial ==="
./zsimpletest < input_simpletest_cmplx
./zsimpletest_save_restore < input_simpletest_cmplx
