#!/bin/sh -e

# serial tests, but still compile against MPI libraries
DEFAULT_MPI=$( grep ARCH_DEFAULT_MPI_IMPL /usr/share/mpi-default-dev/debian_defaults | sed "s/ARCH_DEFAULT_MPI_IMPL=//" )

cd examples

cp ../debian/tests/Makefile.inc ..
make clean
make MUMPS_MPI=${DEFAULT_MPI} all

echo "\n=== running c_example (serial) ==="
./c_example
./c_example_save_restore

echo "\n\n=== running simple test: real, single precision, serial ==="
./ssimpletest < input_simpletest_real
./ssimpletest_save_restore < input_simpletest_real

echo "\n\n=== running simple test: real, double precision, serial ==="
./dsimpletest < input_simpletest_real
./dsimpletest_save_restore < input_simpletest_real

echo "\n\n=== running simple test: complex, single precision, serial ==="
./csimpletest < input_simpletest_cmplx
./csimpletest_save_restore < input_simpletest_cmplx

echo "\n\n=== running simple test: complex, double precision, serial ==="
./zsimpletest < input_simpletest_cmplx
./zsimpletest_save_restore < input_simpletest_cmplx
